import subprocess
import os
from urllib.parse import urlparse
from datetime import datetime
import sys
import glob
import re
import time

def resync(url: str):
    """
    Full resync process with recursive handling of YAML files.
    """
    parsed_url = urlparse(url)
    filename = os.path.basename(parsed_url.path)  # e.g., Milestones.xlsx
    basename, _ = os.path.splitext(filename)      # e.g., Milestones

    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    base_dir = os.path.dirname(__file__)

    logs_dir = os.path.join(base_dir, "logs")
    os.makedirs(logs_dir, exist_ok=True)

    log_file = os.path.join(logs_dir, f"{basename}_{timestamp}.log")

    download_script = os.path.join(base_dir, "download.py")
    scope_script = os.path.join(base_dir, "scope.py")
    read_jira_script = os.path.join(base_dir, "read_jira.py")
    update_excel_script = os.path.join(base_dir, "update_excel.py")
    update_sharepoint_script = os.path.join(base_dir, "update_sharepoint.py")

    def run_and_log(cmd, log, desc):
        """Run a command and log output."""
        header = f"\n--- Running {desc} at {datetime.now()} ---\n"
        print(header, end="")
        log.write(header)

        process = subprocess.Popen(
            cmd,
            stdout=subprocess.PIPE,
            stderr=subprocess.STDOUT,
            text=True,
            bufsize=1,
            cwd=base_dir
        )

        output_lines = []
        for line in process.stdout:
            sys.stdout.write(line)
            log.write(line)
            output_lines.append(line.strip())

        process.wait()

        footer = f"--- Finished {desc} at {datetime.now()} ---\n"
        print(footer, end="")
        log.write(footer)

        return output_lines

    def process_yaml(file_url, input_file):
        """
        Given a URL and an input file, run scope.py and then recursively process all generated YAML files.
        """
        # Run scope.py on the input file
        run_and_log(
            ["python", "-u", scope_script, input_file, file_url],
            log,
            f"scope.py {input_file} {file_url}"
        )

        # Find all YAML files generated by scope.py
        yaml_pattern = os.path.join(base_dir, f"{input_file}.*.scope.yaml")
        yaml_files = glob.glob(yaml_pattern)
        if not yaml_files:
            msg = f"No YAML files found matching pattern {yaml_pattern}\n"
            print(msg, end="")
            log.write(msg)
            return


        # Sort YAML files by substring between filename and .scope.yaml
        def extract_substring(path):
            m = re.match(rf"{re.escape(input_file)}\.(.+)\.scope\.yaml", os.path.basename(path))
            return m.group(1) if m else ""

        yaml_files.sort(key=extract_substring)
            
        

        for yaml_file in yaml_files:
            # Extract the substring matched by '*' in filename.*.scope.yaml
            match = re.match(rf"{re.escape(input_file)}\.(.+)\.scope\.yaml", os.path.basename(yaml_file))
            if not match:
                continue
            substring = match.group(1)

            # Define retry loop for this YAML file
            while True:
                # Re-run download.py on the original URL
                run_and_log(["python", "-u", download_script, file_url], log, f"download.py {file_url}")

                # Run scope.py on the input file again
                run_and_log(["python", "-u", scope_script, input_file, file_url], log, f"scope.py {input_file} {file_url}")

                # Generate CSV file for Jira
                jira_csv = f"{input_file}.{substring}.jira.csv"
                run_and_log(
                    ["python", "-u", read_jira_script, yaml_file],
                    log,
                    f"read_jira.py {yaml_file}"
                )

                # Update Excel
                run_and_log(
                    ["python", "-u", update_excel_script, jira_csv, input_file],
                    log,
                    f"update_excel.py {jira_csv} {input_file}"
                )

                # Update SharePoint and capture output
                output_lines = run_and_log(
                    ["python", "-u", update_sharepoint_script, url, f"{input_file}.{substring}.changes.txt"],
                    log,
                    f"update_sharepoint.py {url} {input_file}.{substring}.changes.txt"
                )

                # Check if "Aborting update" is in output
                if any("Aborting update" in line for line in output_lines):
                    wait_msg = f"Aborting update detected for {yaml_file}, waiting 30 seconds before retry...\n"
                    print(wait_msg, end="")
                    log.write(wait_msg)
                    time.sleep(30)
                    continue  # retry the loop
                else:
                    break  # success, move to next yaml_file


    with open(log_file, "a", encoding="utf-8") as log:
        try:
            # Step 1: initial download
            run_and_log(["python", "-u", download_script, url], log, f"download.py {url}")

            # Step 2: initial scope processing
            process_yaml(url, filename)

        except Exception as e:
            err_msg = f"Error running resync: {e}\n"
            print(err_msg, end="")
            log.write(err_msg)
